// Package rules is the catalog of lint rules: one Markdown file per rule
// under catalog/, embedded in the binary. It's the single source for the
// manual's rule catalog (docs/manual/lint-rules.md, generated by
// internal/docgen) and for anything that explains a rule.
//
// A rule file starts with a small header, then the explanation:
//
//	---
//	severity: error | warning | info
//	scope: core | pg
//	status: planned          (optional; omitted for rules that are enforced)
//	title: one sentence, Markdown
//	---
//
//	Why it matters and how to fix it, in Markdown.
package rules

import (
	"embed"
	"fmt"
	"io/fs"
	"slices"
	"strings"
)

//go:embed catalog/*.md
var _catalog embed.FS

// Rule is one catalog entry.
type Rule struct {
	ID       string // e.g. "DAL115"
	Severity string // error, warning or info
	Scope    string // core (any backend) or pg
	Planned  bool   // documented ahead of its implementation
	Title    string // one sentence, Markdown
	Body     string // explanation, Markdown; may be empty
}

// All returns every rule, sorted by ID. It panics if a catalog file is
// malformed, which the package's tests rule out.
func All() []Rule {
	entries, err := fs.Glob(_catalog, "catalog/*.md")
	if err != nil {
		panic(err)
	}
	out := make([]Rule, 0, len(entries))
	for _, name := range entries {
		data, err := _catalog.ReadFile(name)
		if err != nil {
			panic(err)
		}
		r, err := parse(strings.TrimSuffix(strings.TrimPrefix(name, "catalog/"), ".md"), string(data))
		if err != nil {
			panic(fmt.Sprintf("rules: %s: %v", name, err))
		}
		out = append(out, r)
	}
	slices.SortFunc(out, func(a, b Rule) int { return strings.Compare(a.ID, b.ID) })
	return out
}

// Lookup returns the rule with the given ID.
func Lookup(id string) (Rule, bool) {
	i := slices.IndexFunc(All(), func(r Rule) bool { return r.ID == id })
	if i < 0 {
		return Rule{}, false
	}
	return All()[i], true
}

func parse(id, doc string) (Rule, error) {
	rest, ok := strings.CutPrefix(doc, "---\n")
	if !ok {
		return Rule{}, fmt.Errorf("missing header")
	}
	header, body, ok := strings.Cut(rest, "\n---\n")
	if !ok {
		return Rule{}, fmt.Errorf("unterminated header")
	}
	r := Rule{ID: id, Body: strings.TrimSpace(body)}
	for line := range strings.SplitSeq(header, "\n") {
		key, value, ok := strings.Cut(line, ": ")
		if !ok {
			return Rule{}, fmt.Errorf("header line %q: want key: value", line)
		}
		switch key {
		case "severity":
			r.Severity = value
		case "scope":
			r.Scope = value
		case "status":
			if value != "planned" {
				return Rule{}, fmt.Errorf("status %q: only planned is allowed", value)
			}
			r.Planned = true
		case "title":
			r.Title = value
		default:
			return Rule{}, fmt.Errorf("unknown header key %q", key)
		}
	}
	switch {
	case !slices.Contains([]string{"error", "warning", "info"}, r.Severity):
		return Rule{}, fmt.Errorf("severity %q", r.Severity)
	case r.Scope != "core" && r.Scope != "pg":
		return Rule{}, fmt.Errorf("scope %q", r.Scope)
	case r.Title == "":
		return Rule{}, fmt.Errorf("no title")
	}
	return r, nil
}
