version: "2"

run:
  build-tags:
    - integration # lint integration tests too

linters:
  default: standard # errcheck, govet, ineffassign, staticcheck, unused
  enable:
    - misspell
    - revive

formatters:
  enable:
    - gofmt
    - goimports
