// DRAFT: Postgres backend options. These refine the physical schema only; the
// entity and its access patterns are declared with dal.v1 and stay
// backend-neutral. Every option here is optional.
//
// Evolution: this file is bundled in the dalforge binary and only grows.
// Type values are never renumbered or removed. Which Postgres version (or
// extension) a type or feature needs is data in the generator, not here, and
// is linted against the deploy target in dalforge.yaml.
//
// See docs/design.md for the type mapping and index derivation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: dal/pg/v1/options.proto

package pgv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type lists Postgres types with first-class support: the generator knows
// their Go type, pgx codec, sqlc override and keyset encoding. Values are only
// ever added. A value whose type needs a newer Postgres than the floor notes
// it, e.g. "// PG 17+". All values below exist in every supported version.
type Type int32

const (
	Type_TYPE_UNSPECIFIED      Type = 0
	Type_TYPE_TEXT             Type = 1
	Type_TYPE_UUID             Type = 2
	Type_TYPE_BOOLEAN          Type = 3
	Type_TYPE_SMALLINT         Type = 4
	Type_TYPE_INTEGER          Type = 5
	Type_TYPE_BIGINT           Type = 6
	Type_TYPE_REAL             Type = 7
	Type_TYPE_DOUBLE_PRECISION Type = 8
	Type_TYPE_NUMERIC          Type = 9
	Type_TYPE_TIMESTAMPTZ      Type = 10
	Type_TYPE_DATE             Type = 11
	Type_TYPE_JSONB            Type = 12
	Type_TYPE_BYTEA            Type = 13
	Type_TYPE_INET             Type = 14
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0:  "TYPE_UNSPECIFIED",
		1:  "TYPE_TEXT",
		2:  "TYPE_UUID",
		3:  "TYPE_BOOLEAN",
		4:  "TYPE_SMALLINT",
		5:  "TYPE_INTEGER",
		6:  "TYPE_BIGINT",
		7:  "TYPE_REAL",
		8:  "TYPE_DOUBLE_PRECISION",
		9:  "TYPE_NUMERIC",
		10: "TYPE_TIMESTAMPTZ",
		11: "TYPE_DATE",
		12: "TYPE_JSONB",
		13: "TYPE_BYTEA",
		14: "TYPE_INET",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":      0,
		"TYPE_TEXT":             1,
		"TYPE_UUID":             2,
		"TYPE_BOOLEAN":          3,
		"TYPE_SMALLINT":         4,
		"TYPE_INTEGER":          5,
		"TYPE_BIGINT":           6,
		"TYPE_REAL":             7,
		"TYPE_DOUBLE_PRECISION": 8,
		"TYPE_NUMERIC":          9,
		"TYPE_TIMESTAMPTZ":      10,
		"TYPE_DATE":             11,
		"TYPE_JSONB":            12,
		"TYPE_BYTEA":            13,
		"TYPE_INET":             14,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_dal_pg_v1_options_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_dal_pg_v1_options_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_dal_pg_v1_options_proto_rawDescGZIP(), []int{0}
}

// File states what the schema in a file needs from Postgres. The deploy
// target itself (e.g. 16.9) lives in dalforge.yaml; lint fails when the target
// is older than min_version or lacks a declared extension.
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum Postgres major version, e.g. 16. Zero means dalforge's floor.
	MinVersion uint32 `protobuf:"varint,1,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	// Extensions the schema needs, e.g. ["vector"]. Each one is emitted as
	// CREATE EXTENSION IF NOT EXISTS, and every custom_type it provides must be
	// covered by one of them.
	Extensions    []string `protobuf:"bytes,2,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_dal_pg_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_dal_pg_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_dal_pg_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetMinVersion() uint32 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

func (x *File) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Table refines the Postgres table.
type Table struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Explicit indexes. Most indexes are derived from access patterns; declare
	// one here only for partial or covering indexes, or to pin the sort order
	// that List queries without order_by inherit.
	Indexes []*Index `protobuf:"bytes,1,rep,name=indexes,proto3" json:"indexes,omitempty"`
	// Overrides the per-table index budget used by the write-amplification
	// lint. Zero means the project default.
	IndexBudget   uint32 `protobuf:"varint,2,opt,name=index_budget,json=indexBudget,proto3" json:"index_budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_dal_pg_v1_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_dal_pg_v1_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_dal_pg_v1_options_proto_rawDescGZIP(), []int{1}
}

func (x *Table) GetIndexes() []*Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *Table) GetIndexBudget() uint32 {
	if x != nil {
		return x.IndexBudget
	}
	return 0
}

// Index is an explicitly declared index.
type Index struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index name. Defaults to <table>_<col>_<col>_idx.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Key fields (proto field names) in order, each optionally suffixed with
	// ASC or DESC, e.g.
	// ["account_id", "created_at DESC"].
	Columns []string `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// Non-key fields stored in the index (INCLUDE) for index-only scans.
	Include []string `protobuf:"bytes,3,rep,name=include,proto3" json:"include,omitempty"`
	// Predicate for a partial index, as a SQL boolean expression.
	Where         string `protobuf:"bytes,4,opt,name=where,proto3" json:"where,omitempty"`
	Unique        bool   `protobuf:"varint,5,opt,name=unique,proto3" json:"unique,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_dal_pg_v1_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_dal_pg_v1_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_dal_pg_v1_options_proto_rawDescGZIP(), []int{2}
}

func (x *Index) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Index) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Index) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *Index) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

func (x *Index) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

// Column refines the Postgres column.
type Column struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Physical type. When unset it is inferred from the proto type and the
	// dal.v1 format; see docs/design.md for the mapping.
	//
	// Types that are valid to be assigned to PgType:
	//
	//	*Column_Type
	//	*Column_CustomType
	PgType isColumn_PgType `protobuf_oneof:"pg_type"`
	// Column default as a SQL expression, e.g. "now()" or "'pending'".
	Default string `protobuf:"bytes,3,opt,name=default,proto3" json:"default,omitempty"`
	// Go type for a custom_type column, as "import/path.Type", e.g.
	// "github.com/pgvector/pgvector-go.Vector". It's passed to sqlc as a type
	// override and used in the domain struct. Required with custom_type.
	GoType        string `protobuf:"bytes,4,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_dal_pg_v1_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_dal_pg_v1_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_dal_pg_v1_options_proto_rawDescGZIP(), []int{3}
}

func (x *Column) GetPgType() isColumn_PgType {
	if x != nil {
		return x.PgType
	}
	return nil
}

func (x *Column) GetType() Type {
	if x != nil {
		if x, ok := x.PgType.(*Column_Type); ok {
			return x.Type
		}
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *Column) GetCustomType() string {
	if x != nil {
		if x, ok := x.PgType.(*Column_CustomType); ok {
			return x.CustomType
		}
	}
	return ""
}

func (x *Column) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *Column) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

type isColumn_PgType interface {
	isColumn_PgType()
}

type Column_Type struct {
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=dal.pg.v1.Type,oneof"`
}

type Column_CustomType struct {
	// Raw type for anything Type does not cover yet (extension types such as
	// vector(1536), or parameterised types such as numeric(12,2)).
	CustomType string `protobuf:"bytes,2,opt,name=custom_type,json=customType,proto3,oneof"`
}

func (*Column_Type) isColumn_PgType() {}

func (*Column_CustomType) isColumn_PgType() {}

var file_dal_pg_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*File)(nil),
		Field:         51010,
		Name:          "dal.pg.v1.file",
		Tag:           "bytes,51010,opt,name=file",
		Filename:      "dal/pg/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Table)(nil),
		Field:         51010,
		Name:          "dal.pg.v1.table",
		Tag:           "bytes,51010,opt,name=table",
		Filename:      "dal/pg/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Column)(nil),
		Field:         51010,
		Name:          "dal.pg.v1.column",
		Tag:           "bytes,51010,opt,name=column",
		Filename:      "dal/pg/v1/options.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional dal.pg.v1.File file = 51010;
	E_File = &file_dal_pg_v1_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional dal.pg.v1.Table table = 51010;
	E_Table = &file_dal_pg_v1_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional dal.pg.v1.Column column = 51010;
	E_Column = &file_dal_pg_v1_options_proto_extTypes[2]
)

var File_dal_pg_v1_options_proto protoreflect.FileDescriptor

const file_dal_pg_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x17dal/pg/v1/options.proto\x12\tdal.pg.v1\x1a google/protobuf/descriptor.proto\"G\n" +
	"\x04File\x12\x1f\n" +
	"\vmin_version\x18\x01 \x01(\rR\n" +
	"minVersion\x12\x1e\n" +
	"\n" +
	"extensions\x18\x02 \x03(\tR\n" +
	"extensions\"V\n" +
	"\x05Table\x12*\n" +
	"\aindexes\x18\x01 \x03(\v2\x10.dal.pg.v1.IndexR\aindexes\x12!\n" +
	"\findex_budget\x18\x02 \x01(\rR\vindexBudget\"}\n" +
	"\x05Index\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12\x18\n" +
	"\ainclude\x18\x03 \x03(\tR\ainclude\x12\x14\n" +
	"\x05where\x18\x04 \x01(\tR\x05where\x12\x16\n" +
	"\x06unique\x18\x05 \x01(\bR\x06unique\"\x90\x01\n" +
	"\x06Column\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.dal.pg.v1.TypeH\x00R\x04type\x12!\n" +
	"\vcustom_type\x18\x02 \x01(\tH\x00R\n" +
	"customType\x12\x18\n" +
	"\adefault\x18\x03 \x01(\tR\adefault\x12\x17\n" +
	"\ago_type\x18\x04 \x01(\tR\x06goTypeB\t\n" +
	"\apg_type*\x92\x02\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_TEXT\x10\x01\x12\r\n" +
	"\tTYPE_UUID\x10\x02\x12\x10\n" +
	"\fTYPE_BOOLEAN\x10\x03\x12\x11\n" +
	"\rTYPE_SMALLINT\x10\x04\x12\x10\n" +
	"\fTYPE_INTEGER\x10\x05\x12\x0f\n" +
	"\vTYPE_BIGINT\x10\x06\x12\r\n" +
	"\tTYPE_REAL\x10\a\x12\x19\n" +
	"\x15TYPE_DOUBLE_PRECISION\x10\b\x12\x10\n" +
	"\fTYPE_NUMERIC\x10\t\x12\x14\n" +
	"\x10TYPE_TIMESTAMPTZ\x10\n" +
	"\x12\r\n" +
	"\tTYPE_DATE\x10\v\x12\x0e\n" +
	"\n" +
	"TYPE_JSONB\x10\f\x12\x0e\n" +
	"\n" +
	"TYPE_BYTEA\x10\r\x12\r\n" +
	"\tTYPE_INET\x10\x0e:C\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18\u008e\x03 \x01(\v2\x0f.dal.pg.v1.FileR\x04file:I\n" +
	"\x05table\x12\x1f.google.protobuf.MessageOptions\x18\u008e\x03 \x01(\v2\x10.dal.pg.v1.TableR\x05table:J\n" +
	"\x06column\x12\x1d.google.protobuf.FieldOptions\x18\u008e\x03 \x01(\v2\x11.dal.pg.v1.ColumnR\x06columnB2Z0github.com/gisripa/dalforge/proto/dal/pg/v1;pgv1b\x06proto3"

var (
	file_dal_pg_v1_options_proto_rawDescOnce sync.Once
	file_dal_pg_v1_options_proto_rawDescData []byte
)

func file_dal_pg_v1_options_proto_rawDescGZIP() []byte {
	file_dal_pg_v1_options_proto_rawDescOnce.Do(func() {
		file_dal_pg_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dal_pg_v1_options_proto_rawDesc), len(file_dal_pg_v1_options_proto_rawDesc)))
	})
	return file_dal_pg_v1_options_proto_rawDescData
}

var file_dal_pg_v1_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dal_pg_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dal_pg_v1_options_proto_goTypes = []any{
	(Type)(0),                           // 0: dal.pg.v1.Type
	(*File)(nil),                        // 1: dal.pg.v1.File
	(*Table)(nil),                       // 2: dal.pg.v1.Table
	(*Index)(nil),                       // 3: dal.pg.v1.Index
	(*Column)(nil),                      // 4: dal.pg.v1.Column
	(*descriptorpb.FileOptions)(nil),    // 5: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 6: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 7: google.protobuf.FieldOptions
}
var file_dal_pg_v1_options_proto_depIdxs = []int32{
	3, // 0: dal.pg.v1.Table.indexes:type_name -> dal.pg.v1.Index
	0, // 1: dal.pg.v1.Column.type:type_name -> dal.pg.v1.Type
	5, // 2: dal.pg.v1.file:extendee -> google.protobuf.FileOptions
	6, // 3: dal.pg.v1.table:extendee -> google.protobuf.MessageOptions
	7, // 4: dal.pg.v1.column:extendee -> google.protobuf.FieldOptions
	1, // 5: dal.pg.v1.file:type_name -> dal.pg.v1.File
	2, // 6: dal.pg.v1.table:type_name -> dal.pg.v1.Table
	4, // 7: dal.pg.v1.column:type_name -> dal.pg.v1.Column
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	5, // [5:8] is the sub-list for extension type_name
	2, // [2:5] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dal_pg_v1_options_proto_init() }
func file_dal_pg_v1_options_proto_init() {
	if File_dal_pg_v1_options_proto != nil {
		return
	}
	file_dal_pg_v1_options_proto_msgTypes[3].OneofWrappers = []any{
		(*Column_Type)(nil),
		(*Column_CustomType)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dal_pg_v1_options_proto_rawDesc), len(file_dal_pg_v1_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_dal_pg_v1_options_proto_goTypes,
		DependencyIndexes: file_dal_pg_v1_options_proto_depIdxs,
		EnumInfos:         file_dal_pg_v1_options_proto_enumTypes,
		MessageInfos:      file_dal_pg_v1_options_proto_msgTypes,
		ExtensionInfos:    file_dal_pg_v1_options_proto_extTypes,
	}.Build()
	File_dal_pg_v1_options_proto = out.File
	file_dal_pg_v1_options_proto_goTypes = nil
	file_dal_pg_v1_options_proto_depIdxs = nil
}
