// Package pipeline runs dalforge end to end: load the IDL, validate it,
// build the backend model, emit files, and (for generate) write them and run
// sqlc. The CLI is a thin layer over it.
package pipeline

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"slices"
	"strings"

	"github.com/gisripa/dalforge/internal/backend/pg"
	"github.com/gisripa/dalforge/internal/check"
	"github.com/gisripa/dalforge/internal/config"
	"github.com/gisripa/dalforge/internal/diag"
	"github.com/gisripa/dalforge/internal/idl"
)

// Plan is what a run would produce, before anything touches disk.
type Plan struct {
	Files map[string][]byte // slash-separated paths relative to the project root
	Diags diag.List
}

// _bundled are the options files served from the binary; a vendored copy
// under a proto root is never an input.
var _bundled = []string{"dal/v1/options.proto", "dal/pg/v1/options.proto"}

// Build loads, validates and emits. It stops before emitting when validation
// reports errors; Files is then empty. A non-nil error means the IDL could
// not be loaded at all (structural problems), not lint findings.
func Build(ctx context.Context, cfg *config.Config) (*Plan, error) {
	files, err := protoFiles(cfg)
	if err != nil {
		return nil, err
	}
	roots := make([]string, len(cfg.Proto.Roots))
	for i, r := range cfg.Proto.Roots {
		roots[i] = cfg.Path(r)
	}
	res, err := idl.Load(ctx, files, idl.Options{ImportPaths: roots})
	if err != nil {
		return nil, err
	}

	plan := &Plan{Files: map[string][]byte{}}
	v, err := vendored(ctx, cfg)
	if err != nil {
		return nil, err
	}
	plan.Diags = append(plan.Diags, v...)
	plan.Diags = append(plan.Diags, check.Schema(res.Schema)...)
	if plan.Diags.HasErrors() {
		return plan, nil
	}
	major, err := cfg.PGMajor()
	if err != nil {
		return nil, err
	}
	model, d := pg.Build(res.Schema, res.PG, pg.Target{Major: major})
	plan.Diags = append(plan.Diags, d...)
	if plan.Diags.HasErrors() {
		return plan, nil
	}
	out, d := pg.Emit(res.Schema, model, pg.Layout{
		Module:    cfg.Module,
		Schema:    cfg.Out.Schema,
		Generated: cfg.Out.Queries,
		Custom:    cfg.Out.Custom,
		SQLCOut:   cfg.Out.SQLC,
		Package:   path.Base(cfg.Out.SQLC),
		DALRoot:   cfg.Out.DAL,
	})
	plan.Diags = append(plan.Diags, d...)
	plan.Diags.Sort()
	if !plan.Diags.HasErrors() {
		plan.Files = out
	}
	return plan, nil
}

// protoFiles lists the input files, relative to the proto roots: the
// configured globs, or every .proto under the roots.
func protoFiles(cfg *config.Config) ([]string, error) {
	seen := map[string]bool{}
	var out []string
	add := func(rel string) {
		rel = filepath.ToSlash(rel)
		if !seen[rel] && !slices.Contains(_bundled, rel) {
			seen[rel] = true
			out = append(out, rel)
		}
	}
	for _, root := range cfg.Proto.Roots {
		dir := cfg.Path(root)
		if len(cfg.Proto.Files) == 0 {
			err := filepath.WalkDir(dir, func(p string, d fs.DirEntry, err error) error {
				if err != nil || d.IsDir() || !strings.HasSuffix(p, ".proto") {
					return err
				}
				rel, err := filepath.Rel(dir, p)
				if err == nil {
					add(rel)
				}
				return err
			})
			if err != nil {
				return nil, fmt.Errorf("proto.roots %q: %w", root, err)
			}
			continue
		}
		for _, pattern := range cfg.Proto.Files {
			matches, err := filepath.Glob(filepath.Join(dir, filepath.FromSlash(pattern)))
			if err != nil {
				return nil, fmt.Errorf("proto.files %q: %w", pattern, err)
			}
			for _, m := range matches {
				rel, err := filepath.Rel(dir, m)
				if err != nil {
					return nil, err
				}
				add(rel)
			}
		}
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("no .proto files found under proto.roots %v (files: %v)", cfg.Proto.Roots, cfg.Proto.Files)
	}
	slices.Sort(out)
	return out, nil
}

// Summary reports what Generate did.
type Summary struct {
	Written, Unchanged, Removed int
	RanSQLC                     bool
	SQLCNote                    string // why sqlc was skipped
}

// Generate applies a plan to the project: it writes changed files, removes
// stale generated files, and runs sqlc. It only ever deletes files carrying a
// "Code generated by dalforge" or "Code generated by sqlc" header, and never
// touches the custom queries directory.
func Generate(ctx context.Context, cfg *config.Config, plan *Plan, sqlc string) (Summary, error) {
	var sum Summary
	for _, rel := range sortedKeys(plan.Files) {
		changed, err := writeIfChanged(cfg.Path(rel), plan.Files[rel])
		if err != nil {
			return sum, err
		}
		if changed {
			sum.Written++
		} else {
			sum.Unchanged++
		}
	}

	// Stale dalforge output: generated files no longer in the plan.
	for _, dir := range []string{cfg.Out.Queries, cfg.Out.DAL} {
		removed, err := removeStale(cfg.Path(dir), cfg.Root, _dalforgeHeaders, plan.Files, cfg.Path(cfg.Out.Custom))
		if err != nil {
			return sum, err
		}
		sum.Removed += len(removed)
	}

	if err := os.MkdirAll(cfg.Path(cfg.Out.Custom), 0o755); err != nil {
		return sum, err
	}
	hasQueries, err := anyQueries(cfg, plan)
	if err != nil {
		return sum, err
	}
	if !hasQueries {
		sum.SQLCNote = "no queries yet (no stores and no custom queries); sqlc skipped"
		return sum, nil
	}

	// sqlc doesn't remove output for queries that disappeared; clear its
	// previous output first. Only files sqlc doesn't recreate count as stale.
	cleared, err := removeStale(cfg.Path(cfg.Out.SQLC), cfg.Root, []string{"// Code generated by sqlc. DO NOT EDIT."}, nil, "")
	if err != nil {
		return sum, err
	}
	if err := runSQLC(ctx, sqlc, cfg.Root); err != nil {
		return sum, err
	}
	sum.RanSQLC = true
	for _, f := range cleared {
		if _, err := os.Stat(f); errors.Is(err, fs.ErrNotExist) {
			sum.Removed++
		}
	}
	return sum, nil
}

var _dalforgeHeaders = []string{
	"-- Code generated by dalforge. DO NOT EDIT.",
	"// Code generated by dalforge. DO NOT EDIT.",
	"# Code generated by dalforge. DO NOT EDIT.",
}

func writeIfChanged(file string, data []byte) (bool, error) {
	if old, err := os.ReadFile(file); err == nil && bytes.Equal(old, data) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(file), 0o755); err != nil {
		return false, err
	}
	return true, os.WriteFile(file, data, 0o644)
}

// removeStale deletes files under dir that start with one of headers and
// aren't in keep (keyed by root-relative slash path), returning their paths.
// It skips the custom directory entirely.
func removeStale(dir, root string, headers []string, keep map[string][]byte, custom string) ([]string, error) {
	var removed []string
	err := filepath.WalkDir(dir, func(p string, d fs.DirEntry, err error) error {
		if errors.Is(err, fs.ErrNotExist) && p == dir {
			return fs.SkipAll
		}
		if err != nil {
			return err
		}
		if d.IsDir() {
			if custom != "" && p == custom {
				return fs.SkipDir
			}
			return nil
		}
		rel, err := filepath.Rel(root, p)
		if err != nil {
			return err
		}
		if _, ok := keep[filepath.ToSlash(rel)]; ok {
			return nil
		}
		generated, err := hasHeader(p, headers)
		if err != nil || !generated {
			return err
		}
		removed = append(removed, p)
		return os.Remove(p)
	})
	return removed, err
}

func hasHeader(file string, headers []string) (bool, error) {
	f, err := os.Open(file)
	if err != nil {
		return false, err
	}
	defer func() { _ = f.Close() }() // read-only; a close error can't lose data
	buf := make([]byte, 128)
	n, err := io.ReadFull(f, buf)
	if err != nil && !errors.Is(err, io.ErrUnexpectedEOF) && !errors.Is(err, io.EOF) {
		return false, err
	}
	first, _, _ := strings.Cut(string(buf[:n]), "\n")
	return slices.Contains(headers, strings.TrimSpace(first)), nil
}

// anyQueries reports whether sqlc has anything to compile: a generated query
// or a custom .sql file. sqlc fails when there are none.
func anyQueries(cfg *config.Config, plan *Plan) (bool, error) {
	prefix := strings.TrimSuffix(filepath.ToSlash(cfg.Out.Queries), "/") + "/"
	for rel, body := range plan.Files {
		if strings.HasPrefix(rel, prefix) && bytes.Contains(body, []byte("-- name: ")) {
			return true, nil
		}
	}
	entries, err := os.ReadDir(cfg.Path(cfg.Out.Custom))
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return false, err
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".sql") {
			return true, nil
		}
	}
	return false, nil
}

// FindSQLC returns sqlc's path, or an error explaining how to get it.
func FindSQLC() (string, error) {
	p, err := exec.LookPath("sqlc")
	if err != nil {
		return "", errors.New(`sqlc not found on PATH; pin it in your mise.toml ([tools] sqlc = "1.31")`)
	}
	return p, nil
}

func runSQLC(ctx context.Context, sqlc, root string) error {
	cmd := exec.CommandContext(ctx, sqlc, "generate")
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("sqlc generate: %w\n%s", err, out)
	}
	return nil
}

func sortedKeys(m map[string][]byte) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}
