package pipeline

import (
	"context"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/gisripa/dalforge/internal/config"
)

// project creates a throwaway project: dalforge.yaml plus fixture protos
// copied from the loader's testdata.
func project(t *testing.T, yaml string, protos ...string) *config.Config {
	t.Helper()
	dir := t.TempDir()
	write(t, filepath.Join(dir, config.DefaultFile), yaml)
	for _, p := range protos {
		src, err := os.ReadFile(filepath.Join("..", "idl", "testdata", filepath.FromSlash(p)))
		if err != nil {
			t.Fatal(err)
		}
		write(t, filepath.Join(dir, "proto", filepath.FromSlash(p)), string(src))
	}
	cfg, err := config.Load(filepath.Join(dir, config.DefaultFile))
	if err != nil {
		t.Fatal(err)
	}
	return cfg
}

func write(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

const _yaml = "version: 1\nmodule: example.com/shop\npg:\n  version: \"16.9\"\n"

func TestBuildPlansFiles(t *testing.T) {
	cfg := project(t, _yaml+"out:\n  sqlc: internal/db\n  dal: internal/dal\n", "orders/v1/orders.proto")
	plan, err := Build(context.Background(), cfg)
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Diags) > 0 {
		t.Fatalf("findings:\n%s", plan.Diags)
	}
	var got []string
	for p := range plan.Files {
		got = append(got, p)
	}
	slices.Sort(got)
	want := []string{
		"internal/dal/orders/v1/ordersdal/dal.go",
		"internal/dal/orders/v1/ordersdal/repository.go",
		"queries/generated/orders.sql",
		"schema/schema.sql",
		"sqlc.yaml",
	}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Errorf("planned files:\n%s\nwant:\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}
	// The custom layout flows through: sqlc's package and the DAL's import.
	if !strings.Contains(string(plan.Files["sqlc.yaml"]), "package: db") ||
		!strings.Contains(string(plan.Files["internal/dal/orders/v1/ordersdal/dal.go"]), `"example.com/shop/internal/db"`) {
		t.Error("custom out.sqlc must set sqlc's package and the DAL's import path")
	}
}

func TestBuildStopsOnFindings(t *testing.T) {
	cfg := project(t, _yaml, "orders/v1/orders.proto")
	// An IDL error the core checks catch: a typo in a list's eq.
	p := cfg.Path("proto/orders/v1/orders.proto")
	src, _ := os.ReadFile(p)
	write(t, p, strings.Replace(string(src), `eq: ["account_id"]`, `eq: ["acount_id"]`, 1))

	plan, err := Build(context.Background(), cfg)
	if err != nil {
		t.Fatal(err)
	}
	if !plan.Diags.HasErrors() || len(plan.Files) != 0 || !strings.Contains(plan.Diags.String(), "DAL117") {
		t.Errorf("want a DAL117 error and no planned files; got %d files and:\n%s", len(plan.Files), plan.Diags)
	}
}

func TestBuildTargetVersion(t *testing.T) {
	// The orders fixture needs PG 16; a pg.version of 15 is below dalforge's floor.
	cfg := project(t, "version: 1\nmodule: m\npg:\n  version: \"15.4\"\n", "orders/v1/orders.proto")
	plan, err := Build(context.Background(), cfg)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(plan.Diags.String(), "DAL207") {
		t.Errorf("want DAL207 for pg.version 15; got:\n%s", plan.Diags)
	}
}

func TestProtoFiles(t *testing.T) {
	cfg := project(t, _yaml, "orders/v1/orders.proto", "shop/v1/account.proto", "shop/v1/stores.proto")
	// A vendored copy of the options must never become an input.
	write(t, cfg.Path("proto/dal/v1/options.proto"), "syntax = \"proto3\";\n")

	all, err := protoFiles(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if got := strings.Join(all, ","); got != "orders/v1/orders.proto,shop/v1/account.proto,shop/v1/stores.proto" {
		t.Errorf("default discovery = %s", got)
	}

	cfg.Proto.Files = []string{"shop/v1/*.proto"}
	some, err := protoFiles(cfg)
	if err != nil || strings.Join(some, ",") != "shop/v1/account.proto,shop/v1/stores.proto" {
		t.Errorf("glob = %v, %v", some, err)
	}

	cfg.Proto.Files = []string{"nothing/*.proto"}
	if _, err := protoFiles(cfg); err == nil {
		t.Error("no matching files must be an error")
	}
}

func sqlcOrSkip(t *testing.T) string {
	t.Helper()
	p, err := FindSQLC()
	if err != nil {
		if os.Getenv("CI") != "" {
			t.Fatal(err)
		}
		t.Skip(err)
	}
	return p
}

func TestGenerate(t *testing.T) {
	sqlc := sqlcOrSkip(t)
	ctx := context.Background()
	cfg := project(t, _yaml, "orders/v1/orders.proto")

	// Pre-existing files: a stale generated file, a hand-written file inside
	// a generated directory (no header), and a custom query.
	write(t, cfg.Path("queries/generated/old.sql"), "-- Code generated by dalforge. DO NOT EDIT.\n-- stale\n")
	write(t, cfg.Path("queries/generated/NOTES.md"), "hand-written, keep me\n")
	custom := "-- name: OrderCountByStatus :one\nSELECT count(*) FROM orders WHERE status = @status;\n"
	write(t, cfg.Path("queries/custom/reports.sql"), custom)

	plan, err := Build(ctx, cfg)
	if err != nil || plan.Diags.HasErrors() {
		t.Fatalf("Build: %v\n%s", err, plan.Diags)
	}
	sum, err := Generate(ctx, cfg, plan, sqlc)
	if err != nil {
		t.Fatal(err)
	}
	if sum.Written != len(plan.Files) || sum.Removed != 1 || !sum.RanSQLC {
		t.Errorf("summary = %+v; want %d written, 1 removed, sqlc ran", sum, len(plan.Files))
	}

	exists := func(rel string) bool { _, err := os.Stat(cfg.Path(rel)); return err == nil }
	for _, rel := range []string{"schema/schema.sql", "sqlc.yaml", "gen/sqlcdb/models.go", "gen/sqlcdb/reports.sql.go", "gen/orders/v1/ordersdal/repository.go"} {
		if !exists(rel) {
			t.Errorf("%s was not generated", rel)
		}
	}
	if exists("queries/generated/old.sql") {
		t.Error("the stale generated file must be removed")
	}
	if !exists("queries/generated/NOTES.md") {
		t.Error("a file without the generated header must never be removed")
	}
	if got, _ := os.ReadFile(cfg.Path("queries/custom/reports.sql")); string(got) != custom {
		t.Error("custom queries must never be touched")
	}

	// The output compiles as part of the project... at least, sqlc accepted
	// the custom query alongside the generated ones (reports.sql.go exists).
	// A second run changes nothing.
	sum, err = Generate(ctx, cfg, plan, sqlc)
	if err != nil || sum.Written != 0 || sum.Unchanged != len(plan.Files) || sum.Removed != 0 {
		t.Errorf("second run = %+v, %v; want everything unchanged", sum, err)
	}
}

func TestGenerateRemovesStaleSQLCOutput(t *testing.T) {
	sqlc := sqlcOrSkip(t)
	ctx := context.Background()
	cfg := project(t, _yaml, "orders/v1/orders.proto")
	write(t, cfg.Path("gen/sqlcdb/gone.sql.go"), "// Code generated by sqlc. DO NOT EDIT.\npackage sqlcdb\n")

	plan, _ := Build(ctx, cfg)
	if _, err := Generate(ctx, cfg, plan, sqlc); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(cfg.Path("gen/sqlcdb/gone.sql.go")); err == nil {
		t.Error("stale sqlc output for a removed query file must be removed")
	}
}

func TestGenerateWithoutQueriesSkipsSQLC(t *testing.T) {
	ctx := context.Background()
	cfg := project(t, _yaml, "orders/v1/orders.proto")
	// Drop the store: entities only, no queries anywhere.
	p := cfg.Path("proto/orders/v1/orders.proto")
	src, _ := os.ReadFile(p)
	write(t, p, string(src[:strings.Index(string(src), "service OrderStore")]))

	plan, err := Build(ctx, cfg)
	if err != nil || plan.Diags.HasErrors() {
		t.Fatalf("Build: %v\n%s", err, plan.Diags)
	}
	sum, err := Generate(ctx, cfg, plan, "/nonexistent/sqlc") // must not be called
	if err != nil || sum.RanSQLC || !strings.Contains(sum.SQLCNote, "sqlc skipped") {
		t.Errorf("summary = %+v, %v; want sqlc skipped", sum, err)
	}
}

func TestCustomQueryNameCollision(t *testing.T) {
	cfg := project(t, _yaml, "orders/v1/orders.proto")
	write(t, cfg.Path("queries/custom/mine.sql"), "-- a report\n-- name: OrderGetById :one\nSELECT 1;\n-- name: OrderReport :many\nSELECT 1;\n")
	plan, err := Build(context.Background(), cfg)
	if err != nil {
		t.Fatal(err)
	}
	got := plan.Diags.String()
	if !strings.Contains(got, "queries/custom/mine.sql:2:1: error DAL205: custom query OrderGetById") || strings.Contains(got, "OrderReport") || len(plan.Files) != 0 {
		t.Errorf("findings =\n%s\nwant one DAL205 at mine.sql:2 and no files", got)
	}
}
