// Package docgen generates the parts of the user manual (docs/manual) that
// must follow the code exactly: the lint rule catalog (from internal/rules),
// the option reference (from the comments in the options protos) and the
// type-mapping tables (from the Postgres backend itself, by building a probe
// IDL through the real loader and backend).
//
// Whole pages are generated outright. Tables inside hand-written pages sit
// between markers, which Splice replaces:
//
//	<!-- generated:type-defaults:begin -->
//	…
//	<!-- generated:type-defaults:end -->
//
// The package's test fails when a page is stale; `mise run docs` rewrites them.
package docgen

import (
	"fmt"
	"strings"
)

// _header marks generated pages and regions.
const _header = "<!-- Code generated by internal/docgen. DO NOT EDIT; run `mise run docs`. -->"

// Splice replaces the region named name in doc with content. The region must
// exist exactly once.
func Splice(doc, name, content string) (string, error) {
	begin := fmt.Sprintf("<!-- generated:%s:begin -->\n", name)
	end := fmt.Sprintf("<!-- generated:%s:end -->", name)
	i := strings.Index(doc, begin)
	j := strings.Index(doc, end)
	if i < 0 || j < i || strings.Count(doc, begin) != 1 {
		return "", fmt.Errorf("region %q not found exactly once", name)
	}
	return doc[:i+len(begin)] + content + doc[j:], nil
}

// cell makes text safe for a Markdown table cell.
func cell(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	s = strings.ReplaceAll(s, "<", "&lt;") // e.g. <table>_<col>_idx isn't HTML
	return strings.ReplaceAll(s, "|", `\|`)
}

// anchor is GitHub's anchor for a heading.
func anchor(heading string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(heading) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-', r == '_':
			b.WriteRune(r)
		case r == ' ':
			b.WriteByte('-')
		}
	}
	return b.String()
}
