package pg

import (
	"cmp"
	"fmt"
	"go/format"
	"regexp"
	"slices"
	"strings"
	"unicode"

	"github.com/gisripa/dalforge/internal/diag"
	"github.com/gisripa/dalforge/internal/ir"
)

// emitDAL renders one DAL package per proto package: model and params
// aliases over sqlc's output, plus Read/Write/Repository interfaces per store.
// The implementation arrives in step 1.9. Signatures mirror sqlc's: a single
// query parameter is passed inline, several go in sqlc's params struct.
func emitDAL(s *ir.Schema, m *Schema, layout Layout) (map[string][]byte, diag.List) {
	var diags diag.List
	sqlcImport := layout.Module + "/" + layout.SQLCOut

	type pkg struct {
		entities []*Table
		stores   []*ir.Store
	}
	pkgs := map[string]*pkg{}
	get := func(name string) *pkg {
		if p, ok := pkgs[name]; ok {
			return p
		}
		p := &pkg{}
		pkgs[name] = p
		return p
	}
	addEntity := func(p *pkg, t *Table) {
		if !slices.Contains(p.entities, t) {
			p.entities = append(p.entities, t)
		}
	}
	for _, t := range m.Tables {
		addEntity(get(protoPackage(t.Entity)), t)
	}
	for _, st := range s.Stores {
		p := get(protoPackage(st.FullName))
		p.stores = append(p.stores, st)
		if t := m.table(st.Entity); t != nil {
			addEntity(p, t) // a store's package aliases the models it returns
		}
	}

	files := map[string][]byte{}
	for _, name := range sortedKeys(pkgs) {
		p := pkgs[name]
		slices.SortFunc(p.entities, func(a, b *Table) int { return cmp.Compare(modelName(a), modelName(b)) })
		slices.SortFunc(p.stores, func(a, b *ir.Store) int { return cmp.Compare(a.FullName, b.FullName) })

		g := &goFile{imports: map[string]bool{sqlcImport: true}}
		goPkg := dalPackageName(name)
		fmt.Fprintf(&g.body, "// Package %s is the data access layer for the %s IDL, generated by dalforge.\n", goPkg, name)
		fmt.Fprintf(&g.body, "// Services depend on its interfaces; sqlc's Queries, pools and SQL stay behind them.\n")
		fmt.Fprintf(&g.body, "package %s\n\n__IMPORTS__\n", goPkg)

		for _, t := range p.entities {
			fmt.Fprintf(&g.body, "// %s is the %s entity, stored in table %s.\n", modelName(t), t.Entity, t.Name)
			fmt.Fprintf(&g.body, "type %s = %s.%s\n\n", modelName(t), layout.Package, modelName(t))
		}
		for _, st := range p.stores {
			e, t := s.Entity(st.Entity), m.table(st.Entity)
			if e == nil || t == nil {
				continue
			}
			g.store(st, e, t, layout.Package)
		}

		src, err := g.render()
		if err != nil {
			diags.Add(_ruleInternal, diag.Error, ir.Pos{File: name}, "generated DAL package %s is not valid Go: %v", goPkg, err)
			continue
		}
		dir := layout.DALRoot + "/" + strings.ReplaceAll(name, ".", "/") + "/" + goPkg
		files[dir+"/dal.go"] = src
	}
	return files, diags
}

type goFile struct {
	body    strings.Builder
	imports map[string]bool
}

func (g *goFile) use(t GoType) string {
	if t.Import != "" {
		g.imports[t.Import] = true
	}
	return t.String()
}

func (g *goFile) render() ([]byte, error) {
	g.imports["context"] = true
	var std, ext []string
	for imp := range g.imports {
		if strings.Contains(strings.SplitN(imp, "/", 2)[0], ".") {
			ext = append(ext, imp)
		} else {
			std = append(std, imp)
		}
	}
	slices.Sort(std)
	slices.Sort(ext)
	var b strings.Builder
	b.WriteString("import (\n")
	for _, imp := range std {
		fmt.Fprintf(&b, "\t%q\n", imp)
	}
	b.WriteString("\n")
	for _, imp := range ext {
		if alias := pkgName(imp); alias != imp[strings.LastIndex(imp, "/")+1:] {
			fmt.Fprintf(&b, "\t%s %q\n", alias, imp)
			continue
		}
		fmt.Fprintf(&b, "\t%q\n", imp)
	}
	b.WriteString(")\n")
	src := "// Code generated by dalforge. DO NOT EDIT.\n\n" + strings.Replace(g.body.String(), "__IMPORTS__", b.String(), 1)
	return format.Source([]byte(src))
}

// store writes the params aliases and the three interfaces of one store.
func (g *goFile) store(st *ir.Store, e *ir.Entity, t *Table, sqlcPkg string) {
	short := strings.TrimSuffix(st.FullName[strings.LastIndex(st.FullName, ".")+1:], "Store")
	model := modelName(t)

	var reads, writes []string
	for _, q := range st.Queries {
		name := short + q.Method
		sig, alias, ok := g.signature(q, e, t, model, name)
		if !ok {
			line := fmt.Sprintf("\t// %s (%s) arrives in phase 2.\n", q.Method, q.Spec.Kind())
			if q.Spec.Kind() == "list" {
				reads = append(reads, line)
			} else {
				writes = append(writes, line)
			}
			continue
		}
		if alias != "" {
			fmt.Fprintf(&g.body, "// %s are the parameters of %s.%s.\n", alias, short, q.Method)
			if q.Spec.Kind() == "create" {
				fmt.Fprintf(&g.body, "// Every field is a pointer; nil means:\n%s", createNilDoc(e, t))
			}
			fmt.Fprintf(&g.body, "type %s = %s.%s\n\n", alias, sqlcPkg, alias)
		}
		doc := fmt.Sprintf("\t// %s implements %s.%s (%s).\n", q.Method, st.FullName, q.Method, q.Spec.Kind())
		line := doc + "\t" + q.Method + sig + "\n"
		if q.Spec.Kind() == "get" {
			reads = append(reads, line)
		} else {
			writes = append(writes, line)
		}
	}

	fmt.Fprintf(&g.body, "// %sReadRepository holds the read access patterns of %s.\n", short, st.FullName)
	fmt.Fprintf(&g.body, "type %sReadRepository interface {\n%s}\n\n", short, strings.Join(reads, "\n"))
	fmt.Fprintf(&g.body, "// %sWriteRepository holds the write access patterns of %s.\n", short, st.FullName)
	fmt.Fprintf(&g.body, "type %sWriteRepository interface {\n%s}\n\n", short, strings.Join(writes, "\n"))
	fmt.Fprintf(&g.body, "// %sRepository is every access pattern of %s.\n", short, st.FullName)
	fmt.Fprintf(&g.body, "type %sRepository interface {\n\t%sReadRepository\n\t%sWriteRepository\n}\n\n", short, short, short)
}

type param struct {
	name string // proto field name
	typ  GoType
}

// signature returns the Go signature of a query method, the params alias it
// needs (when sqlc uses a struct), and false for kinds not generated yet.
func (g *goFile) signature(q *ir.Query, e *ir.Entity, t *Table, model, name string) (string, string, bool) {
	var params []param
	byColumn := func(fields []string) {
		for _, f := range fields {
			if c := column(t, f); c != nil {
				params = append(params, param{name: f, typ: c.GoType})
			}
		}
	}
	returns := fmt.Sprintf("(%s, error)", model)

	switch s := q.Spec.(type) {
	case *ir.Get:
		byColumn(s.By.Names)
	case *ir.Create:
		for _, f := range e.Fields {
			if c := column(t, f.Name); f.Role == ir.RoleNone && c != nil {
				params = append(params, param{name: f.Name, typ: insertParamType(c)})
			}
		}
	case *ir.Update:
		byColumn(s.Columns.Names)
		byColumn(e.PrimaryKey())
		for _, f := range e.Fields {
			if f.Role == ir.RoleVersion {
				byColumn([]string{f.Name})
			}
		}
	case *ir.Delete:
		byColumn(e.PrimaryKey())
		if !q.Response.Entity {
			returns = "error"
		}
	default:
		return "", "", false
	}

	if len(params) == 1 {
		return fmt.Sprintf("(ctx context.Context, %s %s) %s", goIdent(params[0].name), g.use(params[0].typ), returns), "", true
	}
	alias := name + "Params"
	return fmt.Sprintf("(ctx context.Context, p %s) %s", alias, returns), alias, true
}

// insertParamType is the Go type of a cast, nullable insert parameter: a
// pointer, except types where nil already means NULL.
func insertParamType(c *Column) GoType {
	return withNull(GoType{Import: c.GoType.Import, Name: c.GoType.Name, Slice: c.GoType.Slice}, false)
}

// createNilDoc documents what nil means for each Create parameter.
func createNilDoc(e *ir.Entity, t *Table) string {
	var b strings.Builder
	for _, f := range e.Fields {
		c := column(t, f.Name)
		if c == nil || f.Role != ir.RoleNone {
			continue
		}
		var means string
		switch {
		case f.PrimaryKey && f.Format == ir.FormatUUID:
			means = "a new UUIDv7"
		case c.Default != "":
			means = "the column default " + c.Default
		case f.Nullable:
			means = "NULL"
		default:
			means = "an error (required)"
		}
		fmt.Fprintf(&b, "//   - %s: %s\n", camel(f.Name), means)
	}
	return b.String()
}

var _version = regexp.MustCompile(`^v\d+([a-z]+\d*)?$`)

// protoPackage returns the proto package of a full name ("orders.v1.Order"
// → "orders.v1").
func protoPackage(fullName string) string {
	return fullName[:max(0, strings.LastIndex(fullName, "."))]
}

// dalPackageName names the Go package of a proto package: its last
// non-version segment plus "dal" ("orders.v1" → "ordersdal").
func dalPackageName(protoPkg string) string {
	parts := strings.Split(protoPkg, ".")
	name := parts[len(parts)-1]
	for i := len(parts) - 1; i >= 0; i-- {
		if !_version.MatchString(parts[i]) {
			name = parts[i]
			break
		}
	}
	return strings.ToLower(strings.ReplaceAll(name, "_", "")) + "dal"
}

// goIdent turns a proto field name into a lowerCamel Go parameter name,
// honouring initialisms ("account_id" → "accountID").
func goIdent(field string) string {
	c := camel(field)
	for i, r := range c {
		if !unicode.IsUpper(r) {
			if i > 1 {
				i-- // keep the last capital of a leading initialism: "IDValue" → "idValue"
			}
			return strings.ToLower(c[:i]) + c[i:]
		}
	}
	return strings.ToLower(c) // all initialism, e.g. "id"
}

type conflict struct {
	pos ir.Pos
	msg string
}

// renameConflicts reports tables that need a sqlc rename while a column has
// the same name (sqlc would rename that column's field too).
func renameConflicts(s *ir.Schema, m *Schema) []conflict {
	columns := map[string]string{}
	for _, t := range m.Tables {
		for _, c := range t.Columns {
			if _, ok := columns[c.Name]; !ok {
				columns[c.Name] = t.Name
			}
		}
	}
	var out []conflict
	for _, r := range modelRenames(m) {
		if owner, ok := columns[r[0]]; ok {
			var pos ir.Pos
			if e := s.Entity(m.tableByName(r[0]).Entity); e != nil {
				pos = e.Pos
			}
			out = append(out, conflict{pos: pos, msg: fmt.Sprintf(
				"table %q must be renamed to %s for sqlc, but %s also has a column %q, whose field sqlc would rename too; change the table or column name",
				r[0], r[1], owner, r[0])})
		}
	}
	return out
}

func (m *Schema) tableByName(name string) *Table {
	for _, t := range m.Tables {
		if t.Name == name {
			return t
		}
	}
	return &Table{}
}
