package pg

import (
	"cmp"
	"fmt"
	"go/format"
	"regexp"
	"slices"
	"strings"
	"unicode"

	"github.com/gisripa/dalforge/internal/diag"
	"github.com/gisripa/dalforge/internal/ir"
)

// emitDAL renders one DAL package per proto package:
//   - dal.go: model and params aliases over sqlc's output, plus
//     Read/Write/Repository interfaces per store;
//   - repository.go: their implementation over sqlc's Queries, run through a
//     dalpg.Runner.
//
// Both files come from the same per-method description, so the interface and
// its implementation can't drift. Signatures mirror sqlc's: a single query
// parameter is passed inline, several go in sqlc's params struct.
func emitDAL(s *ir.Schema, m *Schema, layout Layout) (map[string][]byte, diag.List) {
	var diags diag.List
	sqlcImport := layout.Module + "/" + layout.SQLCOut

	type pkg struct {
		entities []*Table
		stores   []*ir.Store
	}
	pkgs := map[string]*pkg{}
	get := func(name string) *pkg {
		if p, ok := pkgs[name]; ok {
			return p
		}
		p := &pkg{}
		pkgs[name] = p
		return p
	}
	addEntity := func(p *pkg, t *Table) {
		if !slices.Contains(p.entities, t) {
			p.entities = append(p.entities, t)
		}
	}
	for _, t := range m.Tables {
		addEntity(get(protoPackage(t.Entity)), t)
	}
	for _, st := range s.Stores {
		p := get(protoPackage(st.FullName))
		p.stores = append(p.stores, st)
		if t := m.table(st.Entity); t != nil {
			addEntity(p, t) // a store's package aliases the models it returns
		}
	}

	files := map[string][]byte{}
	for _, name := range sortedKeys(pkgs) {
		p := pkgs[name]
		slices.SortFunc(p.entities, func(a, b *Table) int { return cmp.Compare(modelName(a), modelName(b)) })
		slices.SortFunc(p.stores, func(a, b *ir.Store) int { return cmp.Compare(a.FullName, b.FullName) })
		goPkg := dalPackageName(name)
		dir := layout.DALRoot + "/" + strings.ReplaceAll(name, ".", "/") + "/" + goPkg

		api := &goFile{imports: map[string]bool{sqlcImport: true, "context": true}}
		fmt.Fprintf(&api.body, "// Package %s is the data access layer for the %s IDL, generated by dalforge.\n", goPkg, name)
		fmt.Fprintf(&api.body, "// Services depend on its interfaces; sqlc's Queries, pools and SQL stay behind them.\n")
		fmt.Fprintf(&api.body, "package %s\n\n__IMPORTS__\n", goPkg)
		for _, t := range p.entities {
			fmt.Fprintf(&api.body, "// %s is the %s entity, stored in table %s.\n", modelName(t), t.Entity, t.Name)
			fmt.Fprintf(&api.body, "type %s = %s.%s\n\n", modelName(t), layout.Package, modelName(t))
		}

		impl := &goFile{imports: map[string]bool{sqlcImport: true, "context": true,
			_dalImport: true, _dalpgImport: true}}
		fmt.Fprintf(&impl.body, "package %s\n\n__IMPORTS__\n", goPkg)

		for _, st := range p.stores {
			e, t := s.Entity(st.Entity), m.table(st.Entity)
			if e == nil || t == nil {
				continue
			}
			ms, err := methods(st, e, t, m.Paths)
			if err != nil {
				diags.Add(_ruleInternal, diag.Error, st.Pos, "store %s: %v (Emit needs a model Build reported no errors for)", st.FullName, err)
				continue
			}
			api.store(st, ms, layout.Package)
			impl.repository(st, e, t, ms, layout.Package)
		}
		impl.tx(p.stores, name, layout.Package)

		for file, g := range map[string]*goFile{"dal.go": api, "repository.go": impl} {
			src, err := g.render()
			if err != nil {
				diags.Add(_ruleInternal, diag.Error, ir.Pos{File: name}, "generated %s/%s is not valid Go: %v", goPkg, file, err)
				continue
			}
			files[dir+"/"+file] = src
		}
	}
	return files, diags
}

// Runtime packages the generated implementation imports.
const (
	_dalImport   = "github.com/gisripa/dalforge/dal"
	_dalpgImport = "github.com/gisripa/dalforge/dal/dalpg"
)

type goFile struct {
	body    strings.Builder
	imports map[string]bool
}

func (g *goFile) use(t GoType) string {
	if t.Import != "" {
		g.imports[t.Import] = true
	}
	return t.String()
}

func (g *goFile) render() ([]byte, error) {
	var std, ext []string
	for imp := range g.imports {
		if strings.Contains(strings.SplitN(imp, "/", 2)[0], ".") {
			ext = append(ext, imp)
		} else {
			std = append(std, imp)
		}
	}
	slices.Sort(std)
	slices.Sort(ext)
	var b strings.Builder
	b.WriteString("import (\n")
	for _, imp := range std {
		fmt.Fprintf(&b, "\t%q\n", imp)
	}
	b.WriteString("\n")
	for _, imp := range ext {
		if alias := pkgName(imp); alias != imp[strings.LastIndex(imp, "/")+1:] {
			fmt.Fprintf(&b, "\t%s %q\n", alias, imp)
			continue
		}
		fmt.Fprintf(&b, "\t%q\n", imp)
	}
	b.WriteString(")\n")
	src := "// Code generated by dalforge. DO NOT EDIT.\n\n" + strings.Replace(g.body.String(), "__IMPORTS__", b.String(), 1)
	return format.Source([]byte(src))
}

// method describes one generated repository method: everything both the
// interface (dal.go) and its implementation (repository.go) need.
type method struct {
	q       *ir.Query
	rpc     string // Go method name: the rpc name
	sqlc    string // sqlc query name, e.g. "OrderGetById"
	params  []param
	inline  bool   // one parameter, passed inline (as sqlc does)
	alias   string // params struct alias when !inline, e.g. "OrderCreateParams"
	read    bool
	strong  bool // CONSISTENCY_STRONG read
	model   string
	noModel bool   // returns only error (Delete without an entity response)
	execRow bool   // sqlc :execrows (Delete without an entity response)
	nilDoc  string // Create/Update/Upsert: what nil means per written field
	path    *AccessPath
	list    *ir.List // List: the spec
	upsert  bool
	t       *Table
}

// fieldType is a field's Go type in the model.
func (m method) fieldType(field string) GoType {
	if c := column(m.t, field); c != nil {
		return c.GoType
	}
	return GoType{Name: "any"}
}

type param struct {
	name string // proto field name
	typ  GoType
}

// methods builds the method descriptions of a store, mirroring the SQL
// emitter's parameters so the signatures match sqlc's.
func methods(st *ir.Store, e *ir.Entity, t *Table, paths map[string]*AccessPath) ([]method, error) {
	short := storeShort(st)
	var out []method
	for _, q := range st.Queries {
		m := method{q: q, rpc: q.Method, sqlc: short + q.Method, model: modelName(t), t: t}
		byColumn := func(fields []string) {
			for _, f := range fields {
				if c := column(t, f); c != nil {
					m.params = append(m.params, param{name: f, typ: c.GoType})
				}
			}
		}
		switch s := q.Spec.(type) {
		case *ir.Get:
			m.read, m.strong = true, s.Consistency == ir.ConsistencyStrong
			byColumn(s.By.Names)
		case *ir.Create:
			m.nilDoc = createNilDoc(e, t)
			for _, f := range e.Fields {
				if c := column(t, f.Name); f.Role == ir.RoleNone && c != nil {
					m.params = append(m.params, param{name: f.Name, typ: insertParamType(c)})
				}
			}
		case *ir.Update:
			m.nilDoc = updateNilDoc(e, t, s.Columns.Names)
			for _, f := range s.Columns.Names {
				if c := column(t, f); c != nil {
					m.params = append(m.params, param{name: f, typ: insertParamType(c)})
				}
			}
			byColumn(e.PrimaryKey())
			for _, f := range e.Fields {
				if f.Role == ir.RoleVersion {
					byColumn([]string{f.Name})
				}
			}
		case *ir.Delete:
			byColumn(e.PrimaryKey())
			m.noModel, m.execRow = !q.Response.Entity, !q.Response.Entity
		case *ir.List:
			m.read, m.strong = true, s.Consistency == ir.ConsistencyStrong
			m.list, m.path = s, paths[storeShortName(st)+"."+q.Method]
			if m.path == nil {
				return nil, fmt.Errorf("rpc %s has no access path", q.Method)
			}
			m.alias = m.sqlc + "Params" // dalforge-owned (not a sqlc alias)
			out = append(out, m)
			continue
		case *ir.Upsert:
			m.upsert = true
			m.nilDoc = createNilDoc(e, t)
			for _, f := range e.Fields {
				if c := column(t, f.Name); f.Role == ir.RoleNone && c != nil {
					m.params = append(m.params, param{name: f.Name, typ: insertParamType(c)})
				}
			}
		default:
			return nil, fmt.Errorf("rpc %s: no DAL method for %s queries", q.Method, q.Spec.Kind())
		}
		m.inline = len(m.params) == 1
		if !m.inline {
			m.alias = m.sqlc + "Params"
		}
		out = append(out, m)
	}
	return out, nil
}

func storeShort(st *ir.Store) string {
	return strings.TrimSuffix(st.FullName[strings.LastIndex(st.FullName, ".")+1:], "Store")
}

// signature renders "(ctx context.Context, …) (Model, error)".
func (g *goFile) signature(m method) string {
	if m.list != nil {
		g.imports[_dalImport] = true
		return fmt.Sprintf("(ctx context.Context, p %s) (dal.Page[%s], error)", m.alias, m.model)
	}
	arg := "p " + m.alias
	if m.inline {
		arg = goIdent(m.params[0].name) + " " + g.use(m.params[0].typ)
	}
	ret := fmt.Sprintf("(%s, error)", m.model)
	if m.noModel {
		ret = "error"
	}
	return fmt.Sprintf("(ctx context.Context, %s) %s", arg, ret)
}

// listParams writes a List's parameters: the request message's fields, owned
// by dalforge (sqlc's own params carry the cursor and limit instead).
func (g *goFile) listParams(m method, short string) {
	fmt.Fprintf(&g.body, "// %s are the parameters of %s.%s: the filters, plus paging.\n", m.alias, short, m.rpc)
	fmt.Fprintf(&g.body, "// An empty PageToken asks for the first page; PageSize 0 means the default.\n")
	fmt.Fprintf(&g.body, "type %s struct {\n", m.alias)
	for _, f := range listFilterFields(m) {
		fmt.Fprintf(&g.body, "\t%s %s\n", camel(f.name), g.use(f.typ))
	}
	g.body.WriteString("\tPageSize  int32\n\tPageToken string\n}\n\n")
	fmt.Fprintf(&g.body, "// WithPageToken returns p asking for the page at token, for dal.All.\n")
	fmt.Fprintf(&g.body, "func (p %s) WithPageToken(token string) %s {\n\tp.PageToken = token\n\treturn p\n}\n\n", m.alias, m.alias)
}

// listFilterFields are a List's filter parameters: its eq fields, then the
// range bounds <range>_from and <range>_to.
func listFilterFields(m method) []param {
	var out []param
	for _, f := range m.list.Eq {
		out = append(out, param{name: f, typ: m.fieldType(f)})
	}
	if r := m.list.Range; r != "" {
		typ := m.fieldType(r)
		typ.Pointer = false // bounds are required
		out = append(out, param{name: r + "_from", typ: typ}, param{name: r + "_to", typ: typ})
	}
	return out
}

// store writes the params aliases and the three interfaces of one store.
func (g *goFile) store(st *ir.Store, ms []method, sqlcPkg string) {
	short := storeShort(st)
	var reads, writes []string
	for _, m := range ms {
		var line string
		if m.list != nil {
			g.listParams(m, short)
			line = fmt.Sprintf("\t// %s implements %s.%s (%s).\n\t%s%s\n", m.rpc, st.FullName, m.rpc, m.q.Spec.Kind(), m.rpc, g.signature(m))
		} else {
			if m.alias != "" {
				fmt.Fprintf(&g.body, "// %s are the parameters of %s.%s.\n", m.alias, short, m.rpc)
				if m.nilDoc != "" {
					fmt.Fprintf(&g.body, "// Fields to write are pointers; nil means:\n%s", m.nilDoc)
				}
				fmt.Fprintf(&g.body, "type %s = %s.%s\n\n", m.alias, sqlcPkg, m.alias)
			}
			line = fmt.Sprintf("\t// %s implements %s.%s (%s).\n\t%s%s\n", m.rpc, st.FullName, m.rpc, m.q.Spec.Kind(), m.rpc, g.signature(m))
		}
		if m.read {
			reads = append(reads, line)
		} else {
			writes = append(writes, line)
		}
	}
	fmt.Fprintf(&g.body, "// %sReadRepository holds the read access patterns of %s.\n", short, st.FullName)
	fmt.Fprintf(&g.body, "type %sReadRepository interface {\n%s}\n\n", short, strings.Join(reads, "\n"))
	fmt.Fprintf(&g.body, "// %sWriteRepository holds the write access patterns of %s.\n", short, st.FullName)
	fmt.Fprintf(&g.body, "type %sWriteRepository interface {\n%s}\n\n", short, strings.Join(writes, "\n"))
	fmt.Fprintf(&g.body, "// %sRepository is every access pattern of %s.\n", short, st.FullName)
	fmt.Fprintf(&g.body, "type %sRepository interface {\n\t%sReadRepository\n\t%sWriteRepository\n}\n\n", short, short, short)
}

// insertParamType is the Go type of a cast, nullable insert parameter: a
// pointer, except types where nil already means NULL.
func insertParamType(c *Column) GoType {
	return withNull(GoType{Import: c.GoType.Import, Name: c.GoType.Name, Slice: c.GoType.Slice}, false)
}

// updateNilDoc documents what nil means for each field an Update sets. The
// key and version identify the row and stay plain values.
func updateNilDoc(e *ir.Entity, t *Table, fields []string) string {
	var b strings.Builder
	for _, name := range fields {
		f, c := e.Field(name), column(t, name)
		if f == nil || c == nil {
			continue
		}
		means := "an error (required)"
		if f.Nullable {
			means = "set NULL"
		}
		fmt.Fprintf(&b, "//   - %s: %s\n", camel(f.Name), means)
	}
	return b.String()
}

// createNilDoc documents what nil means for each Create parameter.
func createNilDoc(e *ir.Entity, t *Table) string {
	var b strings.Builder
	for _, f := range e.Fields {
		c := column(t, f.Name)
		if c == nil || f.Role != ir.RoleNone {
			continue
		}
		var means string
		switch {
		case f.PrimaryKey && f.Format == ir.FormatUUID:
			means = "a new UUIDv7"
		case c.Default != "":
			means = "the column default " + c.Default
		case f.Nullable:
			means = "NULL"
		default:
			means = "an error (required)"
		}
		fmt.Fprintf(&b, "//   - %s: %s\n", camel(f.Name), means)
	}
	return b.String()
}

var _version = regexp.MustCompile(`^v\d+([a-z]+\d*)?$`)

// protoPackage returns the proto package of a full name ("orders.v1.Order"
// → "orders.v1").
func protoPackage(fullName string) string {
	return fullName[:max(0, strings.LastIndex(fullName, "."))]
}

// dalPackageName names the Go package of a proto package: its last
// non-version segment plus "dal" ("orders.v1" → "ordersdal").
func dalPackageName(protoPkg string) string {
	parts := strings.Split(protoPkg, ".")
	name := parts[len(parts)-1]
	for i := len(parts) - 1; i >= 0; i-- {
		if !_version.MatchString(parts[i]) {
			name = parts[i]
			break
		}
	}
	return strings.ToLower(strings.ReplaceAll(name, "_", "")) + "dal"
}

// goIdent turns a proto field name into a lowerCamel Go parameter name,
// honouring initialisms ("account_id" → "accountID").
func goIdent(field string) string {
	c := camel(field)
	for i, r := range c {
		if !unicode.IsUpper(r) {
			if i > 1 {
				i-- // keep the last capital of a leading initialism: "IDValue" → "idValue"
			}
			return strings.ToLower(c[:i]) + c[i:]
		}
	}
	return strings.ToLower(c) // all initialism, e.g. "id"
}

type conflict struct {
	pos ir.Pos
	msg string
}

// renameConflicts reports tables that need a sqlc rename while a column has
// the same name (sqlc would rename that column's field too).
func renameConflicts(s *ir.Schema, m *Schema) []conflict {
	columns := map[string]string{}
	for _, t := range m.Tables {
		for _, c := range t.Columns {
			if _, ok := columns[c.Name]; !ok {
				columns[c.Name] = t.Name
			}
		}
	}
	var out []conflict
	for _, r := range modelRenames(m) {
		if owner, ok := columns[r[0]]; ok {
			var pos ir.Pos
			if e := s.Entity(m.tableByName(r[0]).Entity); e != nil {
				pos = e.Pos
			}
			out = append(out, conflict{pos: pos, msg: fmt.Sprintf(
				"table %q must be renamed to %s for sqlc, but %s also has a column %q, whose field sqlc would rename too; change the table or column name",
				r[0], r[1], owner, r[0])})
		}
	}
	return out
}

func (m *Schema) tableByName(name string) *Table {
	for _, t := range m.Tables {
		if t.Name == name {
			return t
		}
	}
	return &Table{}
}
