package pg

import (
	"fmt"
	"hash/fnv"
	"slices"
	"strings"

	"github.com/gisripa/dalforge/internal/diag"
	"github.com/gisripa/dalforge/internal/ir"
)

// RuleQueryName reports a sqlc query-name collision (generated vs generated
// here; generated vs custom once custom queries are read).
const RuleQueryName = "DAL205"

// RuleRename reports a table that must be renamed in sqlc (so its model is
// named after the message) while some column has the same name: sqlc's
// rename is global and would rename that column's field too.
const RuleRename = "DAL214"

// RuleParamType reports two columns of one SQL type that need different Go
// types: sqlc's nullable insert-parameter overrides are per type.
const RuleParamType = "DAL213"

// _ruleInternal marks an emitter invariant violation: Emit was called on a
// model that Build reported errors for.
const _ruleInternal = "DAL000"

// _header starts every generated file.
const _header = "-- Code generated by dalforge. DO NOT EDIT.\n"

// Layout is where emitted files go, relative to the output root. The zero
// value uses the defaults from design §9.
type Layout struct {
	// Module is the Go module path of the consuming repo, e.g.
	// "github.com/acme/shop". The DAL package imports sqlc's output through
	// it, so Go files are emitted only when it is set.
	Module    string
	Schema    string // default "schema/schema.sql"
	Generated string // default "queries/generated"
	Custom    string // default "queries/custom": user-owned, never written
	SQLCOut   string // default "gen/sqlcdb"
	Package   string // default "sqlcdb"
	DALRoot   string // default "gen": DAL packages go to <DALRoot>/<proto package path>/<name>dal
}

func (l Layout) withDefaults() Layout {
	set := func(v *string, def string) {
		if *v == "" {
			*v = def
		}
	}
	set(&l.Schema, "schema/schema.sql")
	set(&l.Generated, "queries/generated")
	set(&l.Custom, "queries/custom")
	set(&l.SQLCOut, "gen/sqlcdb")
	set(&l.Package, "sqlcdb")
	set(&l.DALRoot, "gen")
	return l
}

// Emit renders the SQL side of the generated output: the schema, one query
// file per table, and sqlc.yaml. Files are keyed by slash-separated path. The
// model must come from a Build that reported no errors.
func Emit(s *ir.Schema, m *Schema, layout Layout) (map[string][]byte, diag.List) {
	layout = layout.withDefaults()
	files := map[string][]byte{
		layout.Schema: emitSchema(s, m),
		"sqlc.yaml":   emitSQLC(m, layout),
	}
	queries, diags := emitQueries(s, m)
	for _, c := range renameConflicts(s, m) {
		diags.Add(RuleRename, diag.Error, c.pos, "%s", c.msg)
	}
	if layout.Module != "" {
		dal, d := emitDAL(s, m, layout)
		diags = append(diags, d...)
		for path, body := range dal {
			files[path] = body
		}
	}
	if _, conflicts := nullableTypes(m); len(conflicts) > 0 {
		for _, c := range conflicts {
			diags.Add(RuleParamType, diag.Error, ir.Pos{File: layout.Schema, Line: 1, Col: 1},
				"%s; insert parameters are typed per SQL type, so give these fields the same go_type", c)
		}
	}
	for table, body := range queries {
		files[layout.Generated+"/"+table+".sql"] = body
	}
	diags.Sort()
	return files, diags
}

// emitSchema renders the desired-state DDL. Indexes are plain CREATE INDEX:
// migrations (phase 3) decide how to build them on a live database.
func emitSchema(s *ir.Schema, m *Schema) []byte {
	var b strings.Builder
	b.WriteString(_header)
	for _, ext := range m.Extensions {
		fmt.Fprintf(&b, "\nCREATE EXTENSION IF NOT EXISTS %s;\n", ext)
	}
	for _, t := range m.Tables {
		e := s.Entity(t.Entity)
		soft := softDeleteColumn(e, t)

		fmt.Fprintf(&b, "\n-- %s (%s)\nCREATE TABLE %s (\n", t.Entity, t.Pos.File, t.Name)
		for _, c := range t.Columns {
			fmt.Fprintf(&b, "    %s %s", c.Name, c.Type)
			if c.NotNull {
				b.WriteString(" NOT NULL")
			}
			if c.Default != "" {
				fmt.Fprintf(&b, " DEFAULT %s", c.Default)
			}
			if c.Unique && soft == "" {
				b.WriteString(" UNIQUE")
			}
			b.WriteString(",\n")
		}
		fmt.Fprintf(&b, "    PRIMARY KEY (%s)\n);\n", strings.Join(t.PrimaryKey, ", "))

		// On a soft-delete table, uniqueness applies to live rows only, so a
		// deleted row doesn't block re-creating its value.
		for _, c := range t.Columns {
			if c.Unique && soft != "" {
				fmt.Fprintf(&b, "\nCREATE UNIQUE INDEX %s ON %s (%s) WHERE %s IS NULL;\n",
					identName(t.Name, c.Name, "key"), t.Name, c.Name, soft)
			}
		}
		for _, idx := range t.Indexes {
			if idx.Derived {
				fmt.Fprintf(&b, "\n-- derived for: %s", strings.Join(idx.For, ", "))
			}
			b.WriteString("\n" + createIndex(t, idx) + "\n")
		}
	}
	return []byte(b.String())
}

func createIndex(t *Table, idx *Index) string {
	cols := make([]string, len(idx.Columns))
	names := []string{t.Name}
	for i, c := range idx.Columns {
		cols[i] = c.Column
		if c.Desc {
			cols[i] += " DESC"
		}
		names = append(names, c.Column)
	}
	name := idx.Name
	if name == "" {
		name = identName(append(names, "idx")...)
	}
	stmt := "CREATE INDEX"
	if idx.Unique {
		stmt = "CREATE UNIQUE INDEX"
	}
	out := fmt.Sprintf("%s %s ON %s (%s)", stmt, name, t.Name, strings.Join(cols, ", "))
	if len(idx.Include) > 0 {
		out += fmt.Sprintf(" INCLUDE (%s)", strings.Join(idx.Include, ", "))
	}
	if idx.Where != "" {
		out += " WHERE " + idx.Where
	}
	return out + ";"
}

// identName joins parts into a generated identifier. Names over Postgres's
// 63-byte limit are shortened with a hash suffix instead of being silently
// truncated (and possibly colliding).
func identName(parts ...string) string {
	name := strings.Join(parts, "_")
	if len(name) <= _maxIdentifier {
		return name
	}
	h := fnv.New32a()
	h.Write([]byte(name))
	suffix := fmt.Sprintf("_%08x", h.Sum32())
	return name[:_maxIdentifier-len(suffix)] + suffix
}

// softDeleteColumn returns the column of the entity's ROLE_DELETE_TIME field,
// or "".
func softDeleteColumn(e *ir.Entity, t *Table) string {
	return roleColumn(e, t, ir.RoleDeleteTime)
}

func roleColumn(e *ir.Entity, t *Table, role ir.Role) string {
	if e == nil {
		return ""
	}
	for _, f := range e.Fields {
		if c := column(t, f.Name); f.Role == role && c != nil {
			return c.Name
		}
	}
	return ""
}

// column returns the column of a field (by proto field name), or nil when the
// field has none (Build reported why).
func column(t *Table, field string) *Column {
	i := slices.IndexFunc(t.Columns, func(c *Column) bool { return c.Field == field })
	if i < 0 {
		return nil
	}
	return t.Columns[i]
}
