package pg

import (
	"fmt"
	"strings"
)

// emitSQLC renders sqlc.yaml. Every column gets a type override from its
// GoType, so no pgtype wrapper reaches sqlc's models or parameters: the
// generated API exposes no driver types (design §7). Written by hand rather
// than with a YAML library: the shape is fixed and the output must be stable.
func emitSQLC(m *Schema, layout Layout) []byte {
	var b strings.Builder
	b.WriteString("# Code generated by dalforge. DO NOT EDIT.\n")
	fmt.Fprintf(&b, `version: "2"
sql:
  - engine: postgresql
    schema: %s
    queries:
      - %s
      - %s # user-owned: dalforge never writes here
    strict_function_checks: true
    strict_order_by: true
    gen:
      go:
        package: %s
        out: %s
        sql_package: pgx/v5
        emit_interface: true
        emit_pointers_for_null_types: true
        initialisms: [id, ip, url, uri, uuid, http, json, api, sql]
`, layout.Schema, layout.Generated, layout.Custom, layout.Package, layout.SQLCOut)

	if len(m.Tables) == 0 {
		return []byte(b.String())
	}
	b.WriteString("        overrides:\n")
	for _, t := range m.Tables {
		fmt.Fprintf(&b, "          # %s\n", t.Name)
		for _, c := range t.Columns {
			fmt.Fprintf(&b, "          - column: %s.%s\n            go_type:\n", t.Name, c.Name)
			writeGoType(&b, c.GoType)
		}
	}

	nullable, _ := nullableTypes(m)
	if len(nullable) > 0 {
		b.WriteString("          # insert parameters (cast, nullable): every field is a pointer\n")
		for _, n := range nullable {
			fmt.Fprintf(&b, "          - db_type: %s\n            nullable: true\n            go_type:\n", sqlcTypeName(n.dbType))
			writeGoType(&b, n.goType)
		}
	}
	return []byte(b.String())
}

// _sqlcNames maps SQL types to the names sqlc's catalog uses for db_type
// overrides. sqlc is inconsistent here: "numeric" only matches as
// "pg_catalog.numeric", while "timestamptz" only matches unqualified. Found
// with the sqlc feedback test (TestSQLCGenerate), which pins the result.
var _sqlcNames = map[string]string{
	"numeric": "pg_catalog.numeric",
}

func sqlcTypeName(base string) string {
	if n, ok := _sqlcNames[base]; ok {
		return n
	}
	return base
}

// _pointerByDefault lists SQL types sqlc already maps to a clean Go pointer
// when nullable (with emit_pointers_for_null_types), or to a nil-able slice.
var _pointerByDefault = map[string]bool{
	"text": true, "boolean": true, "smallint": true, "integer": true,
	"bigint": true, "real": true, "double precision": true, "bytea": true,
}

type nullableType struct {
	dbType string
	goType GoType
}

// nullableTypes returns the nullable db_type overrides insert parameters
// need: one per SQL base type that sqlc would otherwise map to a pgtype
// wrapper. Overrides are per type, not per column, so two columns of one type
// with different Go types conflict; those are returned as conflicts.
func nullableTypes(m *Schema) ([]nullableType, []string) {
	seen := map[string]GoType{}
	var order []string
	var conflicts []string
	for _, t := range m.Tables {
		for _, c := range t.Columns {
			if strings.HasSuffix(c.Type, "[]") {
				continue // arrays are nil-able slices already
			}
			base := customBase(c.Type)
			if _pointerByDefault[base] {
				continue
			}
			g := withNull(GoType{Import: c.GoType.Import, Name: c.GoType.Name, Slice: c.GoType.Slice}, false)
			if prev, ok := seen[base]; ok {
				if prev != g {
					conflicts = append(conflicts, fmt.Sprintf("%s.%s: SQL type %s maps to %s here but %s elsewhere", t.Name, c.Name, base, g, prev))
				}
				continue
			}
			seen[base] = g
			order = append(order, base)
		}
	}
	out := make([]nullableType, len(order))
	for i, base := range order {
		out[i] = nullableType{dbType: base, goType: seen[base]}
	}
	return out, conflicts
}

// writeGoType renders a sqlc go_type object. "[]byte" is sqlc's
// {type: byte, slice: true}.
func writeGoType(b *strings.Builder, g GoType) {
	const indent = "              "
	name, slice := g.Name, g.Slice
	if name == "[]byte" {
		name, slice = "byte", true
	}
	if g.Import != "" {
		fmt.Fprintf(b, "%simport: %s\n", indent, g.Import)
	}
	fmt.Fprintf(b, "%stype: %s\n", indent, name)
	if g.Pointer {
		fmt.Fprintf(b, "%spointer: true\n", indent)
	}
	if slice {
		fmt.Fprintf(b, "%sslice: true\n", indent)
	}
}
