// Backend-neutral options that turn a protobuf file into a DALForge IDL.
//
// Messages annotated with (dal.v1.table) become entities (a Postgres table, a
// DynamoDB table, ...); fields become columns/attributes. Services annotated
// with (dal.v1.store) declare the access patterns allowed against one entity;
// each rpc carries exactly one (dal.v1.query).
//
// Nothing here may assume a particular store. Physical details live in
// backend option packages such as dal.pg.v1. Everything is optional unless
// noted: the defaults are meant to be the performant choice, and options exist
// only to configure away from them.
//
// Every reference to a field in these options (shard_key, by, eq, range,
// order_by, columns, conflict_on) uses the proto field name, never the SQL
// column name set with (dal.v1.field).name.
//
// See docs/design.md for semantics, defaults and lint rules.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: dal/v1/options.proto

package dalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Format is a logical type layered on a proto scalar.
type Format int32

const (
	Format_FORMAT_UNSPECIFIED Format = 0
	// On string: a UUID. Prefer UUIDv7 for primary keys.
	Format_FORMAT_UUID Format = 1
	// On string: an arbitrary-precision decimal.
	Format_FORMAT_DECIMAL Format = 2
	// On string: a JSON document.
	Format_FORMAT_JSON Format = 3
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_UUID",
		2: "FORMAT_DECIMAL",
		3: "FORMAT_JSON",
	}
	Format_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_UUID":        1,
		"FORMAT_DECIMAL":     2,
		"FORMAT_JSON":        3,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_dal_v1_options_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_dal_v1_options_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{0}
}

// Role marks columns whose values the generated code manages.
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	// On a google.protobuf.Timestamp: set to now() on insert, never updated.
	Role_ROLE_CREATE_TIME Role = 1
	// On a google.protobuf.Timestamp: set to now() on insert and on every
	// update.
	Role_ROLE_UPDATE_TIME Role = 2
	// On an optional google.protobuf.Timestamp: soft delete. Delete sets it,
	// and every generated statement ignores rows where it is set.
	Role_ROLE_DELETE_TIME Role = 3
	// On a required int64 (or int32): optimistic locking. It starts at 1, and
	// every update is a compare-and-swap on it that increments it.
	Role_ROLE_VERSION Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_CREATE_TIME",
		2: "ROLE_UPDATE_TIME",
		3: "ROLE_DELETE_TIME",
		4: "ROLE_VERSION",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_CREATE_TIME": 1,
		"ROLE_UPDATE_TIME": 2,
		"ROLE_DELETE_TIME": 3,
		"ROLE_VERSION":     4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_dal_v1_options_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_dal_v1_options_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{1}
}

// Consistency is the read consistency an rpc needs.
type Consistency int32

const (
	// Unset: eventual.
	Consistency_CONSISTENCY_UNSPECIFIED Consistency = 0
	// Eventual: Postgres reads from the reader pool, which may lag the writer
	// slightly; DynamoDB does an eventually consistent read.
	Consistency_CONSISTENCY_EVENTUAL Consistency = 1
	// Strong, for read-after-write: Postgres reads from the writer pool;
	// DynamoDB sets ConsistentRead (not available on secondary indexes).
	Consistency_CONSISTENCY_STRONG Consistency = 2
)

// Enum value maps for Consistency.
var (
	Consistency_name = map[int32]string{
		0: "CONSISTENCY_UNSPECIFIED",
		1: "CONSISTENCY_EVENTUAL",
		2: "CONSISTENCY_STRONG",
	}
	Consistency_value = map[string]int32{
		"CONSISTENCY_UNSPECIFIED": 0,
		"CONSISTENCY_EVENTUAL":    1,
		"CONSISTENCY_STRONG":      2,
	}
)

func (x Consistency) Enum() *Consistency {
	p := new(Consistency)
	*p = x
	return p
}

func (x Consistency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Consistency) Descriptor() protoreflect.EnumDescriptor {
	return file_dal_v1_options_proto_enumTypes[2].Descriptor()
}

func (Consistency) Type() protoreflect.EnumType {
	return &file_dal_v1_options_proto_enumTypes[2]
}

func (x Consistency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Consistency.Descriptor instead.
func (Consistency) EnumDescriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{2}
}

// Table configures the entity backing a message.
type Table struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Table name. Defaults to the snake_case message name (HTTPRequestLog
	// becomes http_request_log). It must be a valid unquoted identifier
	// (DAL204); a default that's a reserved word, such as order or user, needs
	// an explicit name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Fields the data is sharded by. Recorded and validated (the fields must
	// exist); dalforge doesn't route or enforce it.
	ShardKey      []string `protobuf:"bytes,2,rep,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_dal_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetShardKey() []string {
	if x != nil {
		return x.ShardKey
	}
	return nil
}

// Field configures the column backing a field. Nullability comes from the
// proto field itself: proto3 `optional` fields are nullable, all others are
// required.
//
// To remove a field, delete it and reserve its number and name. Its column is
// retired, not dropped: schema changes are always additive, so code from the
// previous release keeps working.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column name. Defaults to the proto field name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Refines a string field's type: it sets the Go type (e.g. uuid.UUID for
	// FORMAT_UUID) and the column type.
	Format Format `protobuf:"varint,2,opt,name=format,proto3,enum=dal.v1.Format" json:"format,omitempty"`
	// Marks the field as part of the primary key. Multiple fields form a
	// composite key, ordered by their declaration order in the message. A
	// FORMAT_UUID key left nil in a create is assigned a UUIDv7.
	PrimaryKey bool `protobuf:"varint,3,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// Makes the column unique. On an entity with ROLE_DELETE_TIME it's unique
	// among live rows only, so a soft-deleted row doesn't block its value.
	Unique bool `protobuf:"varint,4,opt,name=unique,proto3" json:"unique,omitempty"`
	// Behaviour the generated code manages for this column.
	Role          Role `protobuf:"varint,5,opt,name=role,proto3,enum=dal.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_dal_v1_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{1}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_FORMAT_UNSPECIFIED
}

func (x *Field) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

func (x *Field) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *Field) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

// Store binds a service to the entity whose access patterns it declares.
type Store struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully qualified or file-local name of the entity message, e.g. "Order".
	Entity        string `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_dal_v1_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{2}
}

func (x *Store) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

// Query declares the access pattern implemented by one rpc.
type Query struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Query_Get
	//	*Query_List
	//	*Query_Create
	//	*Query_Update
	//	*Query_Delete
	//	*Query_Upsert
	Kind          isQuery_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_dal_v1_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{3}
}

func (x *Query) GetKind() isQuery_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Query) GetGet() *Get {
	if x != nil {
		if x, ok := x.Kind.(*Query_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *Query) GetList() *List {
	if x != nil {
		if x, ok := x.Kind.(*Query_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Query) GetCreate() *Create {
	if x != nil {
		if x, ok := x.Kind.(*Query_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *Query) GetUpdate() *Update {
	if x != nil {
		if x, ok := x.Kind.(*Query_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *Query) GetDelete() *Delete {
	if x != nil {
		if x, ok := x.Kind.(*Query_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Query) GetUpsert() *Upsert {
	if x != nil {
		if x, ok := x.Kind.(*Query_Upsert); ok {
			return x.Upsert
		}
	}
	return nil
}

type isQuery_Kind interface {
	isQuery_Kind()
}

type Query_Get struct {
	Get *Get `protobuf:"bytes,1,opt,name=get,proto3,oneof"`
}

type Query_List struct {
	List *List `protobuf:"bytes,2,opt,name=list,proto3,oneof"`
}

type Query_Create struct {
	Create *Create `protobuf:"bytes,3,opt,name=create,proto3,oneof"`
}

type Query_Update struct {
	Update *Update `protobuf:"bytes,4,opt,name=update,proto3,oneof"`
}

type Query_Delete struct {
	Delete *Delete `protobuf:"bytes,5,opt,name=delete,proto3,oneof"`
}

type Query_Upsert struct {
	Upsert *Upsert `protobuf:"bytes,6,opt,name=upsert,proto3,oneof"`
}

func (*Query_Get) isQuery_Kind() {}

func (*Query_List) isQuery_Kind() {}

func (*Query_Create) isQuery_Kind() {}

func (*Query_Update) isQuery_Kind() {}

func (*Query_Delete) isQuery_Kind() {}

func (*Query_Upsert) isQuery_Kind() {}

// Get fetches at most one row by a unique key.
type Get struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lookup fields. Defaults to the primary key. Any other set must be
	// covered by a unique field or unique index.
	By []string `protobuf:"bytes,1,rep,name=by,proto3" json:"by,omitempty"`
	// Which copy of the data the read may use. Defaults to eventual.
	Consistency   Consistency `protobuf:"varint,2,opt,name=consistency,proto3,enum=dal.v1.Consistency" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get) Reset() {
	*x = Get{}
	mi := &file_dal_v1_options_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get) ProtoMessage() {}

func (x *Get) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_options_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get.ProtoReflect.Descriptor instead.
func (*Get) Descriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{4}
}

func (x *Get) GetBy() []string {
	if x != nil {
		return x.By
	}
	return nil
}

func (x *Get) GetConsistency() Consistency {
	if x != nil {
		return x.Consistency
	}
	return Consistency_CONSISTENCY_UNSPECIFIED
}

// List pages through rows matching equality filters, using keyset
// pagination: the access path is (eq..., order_by..., primary key).
type List struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Equality filter fields.
	Eq []string `protobuf:"bytes,1,rep,name=eq,proto3" json:"eq,omitempty"`
	// Optional range filter field. It must be the leading order_by field. The
	// filter is half-open: the request carries <range>_from (inclusive) and
	// <range>_to (exclusive), both required.
	Range string `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	// Sort fields, each optionally suffixed with ASC or DESC. When empty, the
	// sort is inherited from a backend-declared index whose leading fields are
	// exactly eq; failing that, it is the primary key. The primary key is
	// always appended as the keyset tie-breaker.
	OrderBy []string `protobuf:"bytes,3,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Page size used when the caller passes 0. Zero here means 50.
	DefaultPageSize uint32 `protobuf:"varint,4,opt,name=default_page_size,json=defaultPageSize,proto3" json:"default_page_size,omitempty"`
	// Largest page size; bigger requests are clamped. Zero here means 500.
	MaxPageSize uint32 `protobuf:"varint,5,opt,name=max_page_size,json=maxPageSize,proto3" json:"max_page_size,omitempty"`
	// Which copy of the data the read may use. Defaults to eventual.
	Consistency   Consistency `protobuf:"varint,6,opt,name=consistency,proto3,enum=dal.v1.Consistency" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *List) Reset() {
	*x = List{}
	mi := &file_dal_v1_options_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_options_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{5}
}

func (x *List) GetEq() []string {
	if x != nil {
		return x.Eq
	}
	return nil
}

func (x *List) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *List) GetOrderBy() []string {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *List) GetDefaultPageSize() uint32 {
	if x != nil {
		return x.DefaultPageSize
	}
	return 0
}

func (x *List) GetMaxPageSize() uint32 {
	if x != nil {
		return x.MaxPageSize
	}
	return 0
}

func (x *List) GetConsistency() Consistency {
	if x != nil {
		return x.Consistency
	}
	return Consistency_CONSISTENCY_UNSPECIFIED
}

// Create inserts one row and returns it. Every field of its parameters is a
// pointer, and nil means the column default, NULL, a new UUIDv7 key, or a
// missing-field error, depending on the field.
type Create struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create) Reset() {
	*x = Create{}
	mi := &file_dal_v1_options_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create) ProtoMessage() {}

func (x *Create) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_options_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create.ProtoReflect.Descriptor instead.
func (*Create) Descriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{6}
}

// Update modifies one row by primary key. When the entity has a ROLE_VERSION
// column the update is a compare-and-swap on it.
type Update struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fields the update may set. Defaults to every non-key field that is not
	// managed by a Role.
	Columns       []string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_dal_v1_options_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_options_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{7}
}

func (x *Update) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Delete removes one row by primary key. When the entity has a
// ROLE_DELETE_TIME column the delete is soft.
type Delete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delete) Reset() {
	*x = Delete{}
	mi := &file_dal_v1_options_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_options_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{8}
}

// Upsert inserts one row, or updates it on conflict. The last writer wins (the
// version is bumped without a compare-and-swap), and a soft-deleted row is
// never revived.
type Upsert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Conflict target fields. Defaults to the primary key; any other set must
	// be covered by a unique field or unique index.
	ConflictOn []string `protobuf:"bytes,1,rep,name=conflict_on,json=conflictOn,proto3" json:"conflict_on,omitempty"`
	// Fields updated on conflict. Defaults to the same set as Update.columns.
	Columns       []string `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upsert) Reset() {
	*x = Upsert{}
	mi := &file_dal_v1_options_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upsert) ProtoMessage() {}

func (x *Upsert) ProtoReflect() protoreflect.Message {
	mi := &file_dal_v1_options_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upsert.ProtoReflect.Descriptor instead.
func (*Upsert) Descriptor() ([]byte, []int) {
	return file_dal_v1_options_proto_rawDescGZIP(), []int{9}
}

func (x *Upsert) GetConflictOn() []string {
	if x != nil {
		return x.ConflictOn
	}
	return nil
}

func (x *Upsert) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

var file_dal_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Table)(nil),
		Field:         51000,
		Name:          "dal.v1.table",
		Tag:           "bytes,51000,opt,name=table",
		Filename:      "dal/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Field)(nil),
		Field:         51000,
		Name:          "dal.v1.field",
		Tag:           "bytes,51000,opt,name=field",
		Filename:      "dal/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Store)(nil),
		Field:         51000,
		Name:          "dal.v1.store",
		Tag:           "bytes,51000,opt,name=store",
		Filename:      "dal/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Query)(nil),
		Field:         51000,
		Name:          "dal.v1.query",
		Tag:           "bytes,51000,opt,name=query",
		Filename:      "dal/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional dal.v1.Table table = 51000;
	E_Table = &file_dal_v1_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional dal.v1.Field field = 51000;
	E_Field = &file_dal_v1_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional dal.v1.Store store = 51000;
	E_Store = &file_dal_v1_options_proto_extTypes[2]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional dal.v1.Query query = 51000;
	E_Query = &file_dal_v1_options_proto_extTypes[3]
)

var File_dal_v1_options_proto protoreflect.FileDescriptor

const file_dal_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x14dal/v1/options.proto\x12\x06dal.v1\x1a google/protobuf/descriptor.proto\"8\n" +
	"\x05Table\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tshard_key\x18\x02 \x03(\tR\bshardKey\"\xab\x01\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x06format\x18\x02 \x01(\x0e2\x0e.dal.v1.FormatR\x06format\x12\x1f\n" +
	"\vprimary_key\x18\x03 \x01(\bR\n" +
	"primaryKey\x12\x16\n" +
	"\x06unique\x18\x04 \x01(\bR\x06unique\x12 \n" +
	"\x04role\x18\x05 \x01(\x0e2\f.dal.v1.RoleR\x04roleJ\x04\b\x06\x10\aR\x05state\"\x1f\n" +
	"\x05Store\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\"\xfc\x01\n" +
	"\x05Query\x12\x1f\n" +
	"\x03get\x18\x01 \x01(\v2\v.dal.v1.GetH\x00R\x03get\x12\"\n" +
	"\x04list\x18\x02 \x01(\v2\f.dal.v1.ListH\x00R\x04list\x12(\n" +
	"\x06create\x18\x03 \x01(\v2\x0e.dal.v1.CreateH\x00R\x06create\x12(\n" +
	"\x06update\x18\x04 \x01(\v2\x0e.dal.v1.UpdateH\x00R\x06update\x12(\n" +
	"\x06delete\x18\x05 \x01(\v2\x0e.dal.v1.DeleteH\x00R\x06delete\x12(\n" +
	"\x06upsert\x18\x06 \x01(\v2\x0e.dal.v1.UpsertH\x00R\x06upsertB\x06\n" +
	"\x04kind\"L\n" +
	"\x03Get\x12\x0e\n" +
	"\x02by\x18\x01 \x03(\tR\x02by\x125\n" +
	"\vconsistency\x18\x02 \x01(\x0e2\x13.dal.v1.ConsistencyR\vconsistency\"\xce\x01\n" +
	"\x04List\x12\x0e\n" +
	"\x02eq\x18\x01 \x03(\tR\x02eq\x12\x14\n" +
	"\x05range\x18\x02 \x01(\tR\x05range\x12\x19\n" +
	"\border_by\x18\x03 \x03(\tR\aorderBy\x12*\n" +
	"\x11default_page_size\x18\x04 \x01(\rR\x0fdefaultPageSize\x12\"\n" +
	"\rmax_page_size\x18\x05 \x01(\rR\vmaxPageSize\x125\n" +
	"\vconsistency\x18\x06 \x01(\x0e2\x13.dal.v1.ConsistencyR\vconsistency\"\b\n" +
	"\x06Create\"\"\n" +
	"\x06Update\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\"\b\n" +
	"\x06Delete\"C\n" +
	"\x06Upsert\x12\x1f\n" +
	"\vconflict_on\x18\x01 \x03(\tR\n" +
	"conflictOn\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns*V\n" +
	"\x06Format\x12\x16\n" +
	"\x12FORMAT_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vFORMAT_UUID\x10\x01\x12\x12\n" +
	"\x0eFORMAT_DECIMAL\x10\x02\x12\x0f\n" +
	"\vFORMAT_JSON\x10\x03*p\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ROLE_CREATE_TIME\x10\x01\x12\x14\n" +
	"\x10ROLE_UPDATE_TIME\x10\x02\x12\x14\n" +
	"\x10ROLE_DELETE_TIME\x10\x03\x12\x10\n" +
	"\fROLE_VERSION\x10\x04*\\\n" +
	"\vConsistency\x12\x1b\n" +
	"\x17CONSISTENCY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CONSISTENCY_EVENTUAL\x10\x01\x12\x16\n" +
	"\x12CONSISTENCY_STRONG\x10\x02:F\n" +
	"\x05table\x12\x1f.google.protobuf.MessageOptions\x18\xb8\x8e\x03 \x01(\v2\r.dal.v1.TableR\x05table:D\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xb8\x8e\x03 \x01(\v2\r.dal.v1.FieldR\x05field:F\n" +
	"\x05store\x12\x1f.google.protobuf.ServiceOptions\x18\xb8\x8e\x03 \x01(\v2\r.dal.v1.StoreR\x05store:E\n" +
	"\x05query\x12\x1e.google.protobuf.MethodOptions\x18\xb8\x8e\x03 \x01(\v2\r.dal.v1.QueryR\x05queryB0Z.github.com/gisripa/dalforge/proto/dal/v1;dalv1b\x06proto3"

var (
	file_dal_v1_options_proto_rawDescOnce sync.Once
	file_dal_v1_options_proto_rawDescData []byte
)

func file_dal_v1_options_proto_rawDescGZIP() []byte {
	file_dal_v1_options_proto_rawDescOnce.Do(func() {
		file_dal_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dal_v1_options_proto_rawDesc), len(file_dal_v1_options_proto_rawDesc)))
	})
	return file_dal_v1_options_proto_rawDescData
}

var file_dal_v1_options_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dal_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dal_v1_options_proto_goTypes = []any{
	(Format)(0),                         // 0: dal.v1.Format
	(Role)(0),                           // 1: dal.v1.Role
	(Consistency)(0),                    // 2: dal.v1.Consistency
	(*Table)(nil),                       // 3: dal.v1.Table
	(*Field)(nil),                       // 4: dal.v1.Field
	(*Store)(nil),                       // 5: dal.v1.Store
	(*Query)(nil),                       // 6: dal.v1.Query
	(*Get)(nil),                         // 7: dal.v1.Get
	(*List)(nil),                        // 8: dal.v1.List
	(*Create)(nil),                      // 9: dal.v1.Create
	(*Update)(nil),                      // 10: dal.v1.Update
	(*Delete)(nil),                      // 11: dal.v1.Delete
	(*Upsert)(nil),                      // 12: dal.v1.Upsert
	(*descriptorpb.MessageOptions)(nil), // 13: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 14: google.protobuf.FieldOptions
	(*descriptorpb.ServiceOptions)(nil), // 15: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 16: google.protobuf.MethodOptions
}
var file_dal_v1_options_proto_depIdxs = []int32{
	0,  // 0: dal.v1.Field.format:type_name -> dal.v1.Format
	1,  // 1: dal.v1.Field.role:type_name -> dal.v1.Role
	7,  // 2: dal.v1.Query.get:type_name -> dal.v1.Get
	8,  // 3: dal.v1.Query.list:type_name -> dal.v1.List
	9,  // 4: dal.v1.Query.create:type_name -> dal.v1.Create
	10, // 5: dal.v1.Query.update:type_name -> dal.v1.Update
	11, // 6: dal.v1.Query.delete:type_name -> dal.v1.Delete
	12, // 7: dal.v1.Query.upsert:type_name -> dal.v1.Upsert
	2,  // 8: dal.v1.Get.consistency:type_name -> dal.v1.Consistency
	2,  // 9: dal.v1.List.consistency:type_name -> dal.v1.Consistency
	13, // 10: dal.v1.table:extendee -> google.protobuf.MessageOptions
	14, // 11: dal.v1.field:extendee -> google.protobuf.FieldOptions
	15, // 12: dal.v1.store:extendee -> google.protobuf.ServiceOptions
	16, // 13: dal.v1.query:extendee -> google.protobuf.MethodOptions
	3,  // 14: dal.v1.table:type_name -> dal.v1.Table
	4,  // 15: dal.v1.field:type_name -> dal.v1.Field
	5,  // 16: dal.v1.store:type_name -> dal.v1.Store
	6,  // 17: dal.v1.query:type_name -> dal.v1.Query
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	14, // [14:18] is the sub-list for extension type_name
	10, // [10:14] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_dal_v1_options_proto_init() }
func file_dal_v1_options_proto_init() {
	if File_dal_v1_options_proto != nil {
		return
	}
	file_dal_v1_options_proto_msgTypes[3].OneofWrappers = []any{
		(*Query_Get)(nil),
		(*Query_List)(nil),
		(*Query_Create)(nil),
		(*Query_Update)(nil),
		(*Query_Delete)(nil),
		(*Query_Upsert)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dal_v1_options_proto_rawDesc), len(file_dal_v1_options_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_dal_v1_options_proto_goTypes,
		DependencyIndexes: file_dal_v1_options_proto_depIdxs,
		EnumInfos:         file_dal_v1_options_proto_enumTypes,
		MessageInfos:      file_dal_v1_options_proto_msgTypes,
		ExtensionInfos:    file_dal_v1_options_proto_extTypes,
	}.Build()
	File_dal_v1_options_proto = out.File
	file_dal_v1_options_proto_goTypes = nil
	file_dal_v1_options_proto_depIdxs = nil
}
